import Arnold.ClosedOpen

/-!
# A fast, verified meander counter

`openMeanderCount n` is defined by filtering all `n!` crossing orders, so it is hopeless to
evaluate beyond `n ≈ 10`. `meanderCount n` is a depth-first search that builds the crossing
order one bridge at a time. It abandons a branch as soon as
* the newest arc crosses an earlier arc on the same side of the road, or
* the **parity test** fails: some drawn arc encloses an odd number of arc ends still to come
  on its side, so the river can never be finished (`parityOK_of_noCross`, a Jordan-curve
  style argument).

`openMeanderCount_eq_meanderCount` proves the search and the definition agree for every `n`.
The proof has two steps:
1. The search equals filtering an explicit list `perms n (List.range n)` of all orderings,
   built by the same recursion, because a pruned branch contains no meanders.
2. Permutations of `Fin n` correspond bijectively to the members of that list (`toList`).
-/

namespace Arnold

open Equiv

/-- All orderings of `rem` (with `k = rem.length`), generated by the same recursion as `dfs`. -/
def perms : ℕ → List ℕ → List (List ℕ)
  | 0, _ => [[]]
  | k + 1, rem => rem.flatMap fun x => (perms k (rem.erase x)).map (x :: ·)

/-! ### `NoCross` bookkeeping -/

theorem noCross_succ (P : ℕ → ℕ) (L : ℕ) :
    NoCross P (L + 1) ↔ NoCross P L ∧
      ∀ j < L, j % 2 = L % 2 → ¬ Interleave (P j) (P (j + 1)) (P L) (P (L + 1)) := by
  constructor
  · intro h
    exact ⟨fun k hk => h k (by omega), h L (by omega)⟩
  · rintro ⟨h1, h2⟩ k hk
    rcases Nat.lt_succ_iff_lt_or_eq.1 hk with h | rfl
    · exact h1 k h
    · exact h2

theorem noCross_mono {P : ℕ → ℕ} {L L' : ℕ} (h : NoCross P L) (hL : L' ≤ L) : NoCross P L' :=
  fun k hk => h k (by omega)

/-- `NoCross P L` only looks at the points `P 0, …, P L`. -/
theorem noCross_congr_pts {P Q : ℕ → ℕ} {L : ℕ} (h : ∀ i ≤ L, P i = Q i) :
    NoCross P L ↔ NoCross Q L :=
  noCross_congr fun k hk j hjk _ => by
    rw [h j (by omega), h (j + 1) (by omega), h k (by omega), h (k + 1) (by omega)]

theorem noCross_lpt_succ (n : ℕ) (q : List ℕ) (t : ℕ) :
    NoCross (lpt n q) (t + 1) ↔ NoCross (lpt n q) t ∧ StepOK n q t :=
  noCross_succ _ _

/-- Appending to the crossing order does not move the points already determined. -/
theorem lpt_append (n : ℕ) (q s : List ℕ) (i : ℕ) (hi : i ≤ q.length) :
    lpt n (q ++ s) i = lpt n q i := by
  unfold lpt
  split_ifs
  · rfl
  · exact List.getD_append _ _ _ _ (by omega)

/-! ### Step 1: the search equals filtering `perms` -/

theorem mem_perms : ∀ (k : ℕ) (rem : List ℕ), rem.length = k →
    ∀ l, l ∈ perms k rem ↔ l.Perm rem := by
  intro k
  induction k with
  | zero =>
    intro rem hrem l
    rw [List.length_eq_zero_iff] at hrem
    subst hrem
    simp [perms]
  | succ k ih =>
    intro rem hrem l
    simp only [perms, List.mem_flatMap, List.mem_map]
    constructor
    · rintro ⟨x, hx, s, hs, rfl⟩
      have hlen : (rem.erase x).length = k := by rw [List.length_erase_of_mem hx]; omega
      exact List.cons_perm_iff_perm_erase.2 ⟨hx, (ih _ hlen s).1 hs⟩
    · intro h
      cases l with
      | nil => simp [List.nil_perm.1 h] at hrem
      | cons x s =>
        obtain ⟨hx, hs⟩ := List.cons_perm_iff_perm_erase.1 h
        have hlen : (rem.erase x).length = k := by rw [List.length_erase_of_mem hx]; omega
        exact ⟨x, hx, s, (ih _ hlen s).2 hs, rfl⟩

theorem nodup_perms : ∀ (k : ℕ) (rem : List ℕ), rem.Nodup → (perms k rem).Nodup := by
  intro k
  induction k with
  | zero => intro _ _; simp [perms]
  | succ k ih =>
    intro rem hrem
    refine List.nodup_flatMap.2 ⟨fun x _ => (ih _ (hrem.erase x)).map List.cons_injective, ?_⟩
    refine hrem.imp fun {x y} hxy => ?_
    intro l hl hl'
    simp only [List.mem_map] at hl hl'
    obtain ⟨_, _, rfl⟩ := hl
    obtain ⟨_, _, h⟩ := hl'
    exact hxy (List.cons.inj h).1.symm

/-! ### Soundness of the parity test -/

/-- `1` if point `i` of the path lies strictly inside arc `j`, else `0`. -/
def ind (P : ℕ → ℕ) (j i : ℕ) : ℕ := if inArc P j (P i) = true then 1 else 0

/-- **The parity argument.** Fix a drawn arc `j < t` of a river `P` without self-crossings.
The later arcs on the same side (indices `k ≥ t` with `k ≡ j`) each have both ends inside arc
`j` or both outside, so they put an even number of ends inside it. Going along the river, the
points `t+1, …, n` are each the end of exactly one such arc. The current point `t` and the east
end `n+1` are ends only when their arc is on that side. -/
theorem parity_future (P : ℕ → ℕ) (n t j : ℕ) (hnc : NoCross P (n + 1)) (hj : j < t)
    (ht : t ≤ n) :
    (∑ i ∈ Finset.Ico (t + 1) (n + 1), ind P j i + (if t % 2 = j % 2 then ind P j t else 0) +
      (if n % 2 = j % 2 then ind P j (n + 1) else 0)) % 2 = 0 := by
  -- A later same-side arc `k` has both ends inside arc `j` or neither.
  have harc : ∀ k, j < k → k ≤ n → k % 2 = j % 2 → ind P j (k + 1) = ind P j k := by
    intro k hjk hkn hpar
    have h := hnc k (by omega) j hjk hpar.symm
    unfold Interleave at h
    rw [not_not] at h
    unfold ind inArc
    simp only [decide_eq_true_eq]
    exact if_congr h.symm rfl rfl
  have hind : ∀ i, ind P j i ≤ 1 := fun i => by unfold ind; split <;> omega
  suffices H : ∀ m, t + 1 ≤ m → m ≤ n + 1 →
      (∑ i ∈ Finset.Ico (t + 1) m, ind P j i + (if t % 2 = j % 2 then ind P j t else 0) +
        (if (m - 1) % 2 = j % 2 then ind P j m else 0)) % 2 = 0 by
    simpa using H (n + 1) (by omega) le_rfl
  intro m hm
  induction m, hm using Nat.le_induction with
  | base =>
    intro _
    simp only [Finset.Ico_self, Finset.sum_empty, zero_add, Nat.add_sub_cancel]
    by_cases hp : t % 2 = j % 2
    · simp only [hp, ↓reduceIte, harc t hj ht hp]
      omega
    · simp [hp]
  | succ m hm ih =>
    intro hm'
    have h := ih (by omega)
    rw [Finset.sum_Ico_succ_top (by omega), Nat.add_sub_cancel]
    by_cases hp : m % 2 = j % 2
    · simp only [show ¬ (m - 1) % 2 = j % 2 by omega, ↓reduceIte, add_zero] at h
      simp only [hp, ↓reduceIte, harc m (by omega) (by omega) hp]
      omega
    · simp only [show (m - 1) % 2 = j % 2 by omega, ↓reduceIte] at h
      simp only [hp, ↓reduceIte, add_zero]
      omega

/-- Counting the entries of `s` with a property, by their positions on the path `q ++ s`. -/
theorem countP_eq_sum (n : ℕ) (g : ℕ → Bool) : ∀ (s q : List ℕ),
    s.countP g = ∑ i ∈ Finset.Ico (q.length + 1) (q.length + s.length + 1),
      (if g (lpt n (q ++ s) i) = true then 1 else 0)
  | [], q => by simp
  | x :: s, q => by
    rw [List.countP_cons, countP_eq_sum n g s (q ++ [x]),
      Finset.sum_eq_sum_Ico_succ_bot (show q.length + 1 < q.length + (x :: s).length + 1 by simp)]
    have hx : lpt n (q ++ x :: s) (q.length + 1) = x := by
      simp [lpt, List.getD_eq_getElem?_getD]
    simp only [List.length_append, List.length_cons, hx, List.append_assoc,
      List.singleton_append]
    rw [show q.length + (s.length + 1) + 1 = q.length + 1 + s.length + 1 by omega]
    by_cases hg : g x = true <;> simp [hg]
    omega

/-- **The parity test is sound**: if `q ++ s` is a meander and `s` uses the bridges `r`, then
`q` passes the parity test with remaining bridges `r`. -/
theorem parityOK_of_noCross (n : ℕ) (q s r : List ℕ) (hlen : q.length + s.length = n)
    (hperm : s.Perm r) (hnc : NoCross (lpt n (q ++ s)) (n + 1)) : ParityOK n q r := by
  intro j hj
  have hPq : ∀ i ≤ q.length, lpt n q i = lpt n (q ++ s) i := fun i hi =>
    (lpt_append n q s i hi).symm
  have hin : inArc (lpt n q) j = inArc (lpt n (q ++ s)) j := by
    funext x
    simp only [inArc, hPq j (by omega), hPq (j + 1) (by omega)]
  have hE : lpt n (q ++ s) (n + 1) = n := by
    simp [lpt, List.getD_eq_getElem?_getD, hlen]
  have h := parity_future (lpt n (q ++ s)) n q.length j hnc hj (by omega)
  unfold futureEnds
  rw [hin, ← hperm.countP_eq, countP_eq_sum n _ s q, hPq q.length le_rfl, hlen]
  have e2 : (if q.length % 2 = j % 2 ∧
      inArc (lpt n (q ++ s)) j (lpt n (q ++ s) q.length) = true then 1 else 0) =
      (if q.length % 2 = j % 2 then ind (lpt n (q ++ s)) j q.length else 0) := by
    unfold ind; split_ifs <;> simp_all
  have e3 : (if n % 2 = j % 2 ∧ inArc (lpt n (q ++ s)) j n = true then 1 else 0) =
      (if n % 2 = j % 2 then ind (lpt n (q ++ s)) j (n + 1) else 0) := by
    unfold ind; rw [hE]; split_ifs <;> simp_all
  rw [e2, e3]
  exact h

theorem dfs_eq (n : ℕ) : ∀ (k : ℕ) (p rem : List ℕ), rem.length = k → p.length + k = n →
    NoCross (lpt n p) p.length →
    dfs n k p rem = (perms k rem).countP (fun s => decide (NoCross (lpt n (p ++ s)) (n + 1))) := by
  intro k
  induction k with
  | zero =>
    intro p rem _ hp hpre
    obtain rfl : n = p.length := by omega
    simp only [dfs, perms, List.countP_cons, List.countP_nil, List.append_nil, zero_add]
    by_cases h : StepOK p.length p p.length <;> simp [noCross_lpt_succ, h, hpre]
  | succ k ih =>
    intro p rem hrem hp hpre
    simp only [dfs, perms, List.countP_flatMap]
    congr 1
    apply List.map_congr_left
    intro x hx
    simp only [Function.comp_apply, List.countP_map]
    have hlen : (rem.erase x).length = k := by
      rw [List.length_erase_of_mem hx]; omega
    split_ifs with hstep
    · rw [ih (p ++ [x]) (rem.erase x) hlen (by simp; omega)]
      · simp [Function.comp_def, List.append_assoc]
      · rw [List.length_append, List.length_singleton, noCross_lpt_succ]
        refine ⟨?_, hstep.1⟩
        exact (noCross_congr_pts fun i hi => lpt_append n p [x] i hi).2 hpre
    · symm
      rw [List.countP_eq_zero]
      intro s hsmem hs
      simp only [Function.comp_apply, decide_eq_true_eq] at hs
      apply hstep
      refine ⟨?_, ?_⟩
      swap
      · -- The parity test is sound: a finished river passes it at every stage.
        have hsperm := (mem_perms k (rem.erase x) hlen s).1 hsmem
        have hslen : s.length = k := by rw [hsperm.length_eq, hlen]
        exact parityOK_of_noCross n (p ++ [x]) s (rem.erase x) (by simp; omega) hsperm
          (by simpa [List.append_assoc] using hs)
      have h1 : NoCross (lpt n ((p ++ [x]) ++ s)) (p.length + 1) :=
        noCross_mono (by simpa [List.append_assoc] using hs) (by omega)
      have h2 : NoCross (lpt n (p ++ [x])) (p.length + 1) :=
        (noCross_congr_pts fun i hi => lpt_append n (p ++ [x]) s i (by simp; omega)).1 h1
      exact ((noCross_lpt_succ n _ _).1 h2).2

/-! ### Step 2: permutations of `Fin n` are the members of `perms n (List.range n)` -/

/-- The crossing order of `σ` as a list of natural numbers. -/
def toList {n : ℕ} (σ : Perm (Fin n)) : List ℕ := List.ofFn fun i => (σ i : ℕ)

theorem pathPt_eq_lpt {n : ℕ} (σ : Perm (Fin n)) (k : ℕ) : pathPt σ k = lpt n (toList σ) k := by
  unfold pathPt lpt toList
  by_cases h0 : k = 0
  · simp [h0]
  · simp only [h0, ↓reduceIte, List.getD_eq_getElem?_getD, List.getElem?_ofFn]
    split_ifs <;> rfl

theorem toList_perm {n : ℕ} (σ : Perm (Fin n)) : (toList σ).Perm (List.range n) := by
  refine (List.perm_ext_iff_of_nodup (List.nodup_ofFn.2 fun i j h => σ.injective (Fin.ext h))
    List.nodup_range).2 fun a => ?_
  simp only [List.mem_ofFn, List.mem_range]
  constructor
  · rintro ⟨i, rfl⟩
    exact (σ i).isLt
  · intro ha
    exact ⟨σ.symm ⟨a, ha⟩, by simp⟩

theorem toList_injective {n : ℕ} : Function.Injective (toList (n := n)) := fun _ _ h =>
  Equiv.ext fun i => Fin.ext (congrFun (List.ofFn_injective h) i)

theorem exists_toList_eq {n : ℕ} {l : List ℕ} (h : l.Perm (List.range n)) :
    ∃ σ : Perm (Fin n), toList σ = l := by
  have hlen : l.length = n := by simpa using h.length_eq
  have hnd : l.Nodup := h.nodup_iff.2 List.nodup_range
  have hlt : ∀ x ∈ l, x < n := fun x hx => List.mem_range.1 (h.subset hx)
  let f : Fin n → Fin n := fun i => ⟨l[i.1]'(by omega), hlt _ (List.getElem_mem _)⟩
  have hf : Function.Injective f := fun i j hij =>
    Fin.ext ((hnd.getElem_inj_iff).1 (congrArg Fin.val hij))
  refine ⟨Equiv.ofBijective f (Finite.injective_iff_bijective.1 hf), ?_⟩
  apply List.ext_getElem (by simp [toList, hlen])
  intro i _ _
  simp [toList, f]

theorem card_eq_countP (n : ℕ) (Q : List ℕ → Prop) [DecidablePred Q] :
    Fintype.card {σ : Perm (Fin n) // Q (toList σ)} =
      (perms n (List.range n)).countP (fun l => decide (Q l)) := by
  have hmem := mem_perms n (List.range n) (by simp)
  rw [Fintype.card_subtype, List.countP_eq_length_filter,
    ← List.toFinset_card_of_nodup ((nodup_perms _ _ List.nodup_range).filter _)]
  apply Finset.card_bij (fun σ _ => toList σ)
  · intro σ hσ
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hσ
    simpa [hmem] using ⟨toList_perm σ, hσ⟩
  · intro σ _ τ _ h
    exact toList_injective h
  · intro l hl
    simp only [List.mem_toFinset, List.mem_filter, decide_eq_true_eq, hmem] at hl
    obtain ⟨σ, rfl⟩ := exists_toList_eq hl.1
    exact ⟨σ, by simpa using hl.2, rfl⟩

/-! ### Main results -/

/-- **The fast search counts exactly Arnold's meanders**, for every `n`. -/
theorem openMeanderCount_eq_meanderCount (n : ℕ) : openMeanderCount n = meanderCount n := by
  have h : openMeanderCount n =
      Fintype.card {σ : Perm (Fin n) // NoCross (lpt n (toList σ)) (n + 1)} :=
    Fintype.card_congr (Equiv.subtypeEquivRight fun σ => by
      rw [IsMeander, show pathPt σ = lpt n (toList σ) from funext (pathPt_eq_lpt σ)])
  rw [h, card_eq_countP n (fun l => NoCross (lpt n l) (n + 1)), meanderCount,
    dfs_eq n n [] (List.range n) (by simp) (by simp) (fun k hk => absurd hk (Nat.not_lt_zero k))]
  simp

/-- Closed meanders of order `n ≥ 1`, counted by the fast search. -/
theorem closedMeanderCount_eq_meanderCount (n : ℕ) (hn : 1 ≤ n) :
    closedMeanderCount n = meanderCount (2 * n - 1) := by
  rw [closedMeanderCount_eq n hn, openMeanderCount_eq_meanderCount]

end Arnold
